print("Hello, please provide your data here: ")
name = input("Please provide your name: ")
height = int(input("Please provide your height: "))
bday = int(input("Please provide your birth day ex. day.month.year: "))
city = str(input("Please provide city where you live: "))
hobby = str(input("Please provide us your hobby: "))
print("Here is your data stats that you entered: ")
print("Your name: ", name)
print("Your height: ", height)
print("Your birth day: ", bday)
print("City where you live: ", city)
print("Your hobby: ", hobby)